server:
  port: 8081

spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}
  application:
    name: stock-service
    version: 1.0.0
    description: A simple gRPC server example
    
  data:
    web:
      pageable:
        one-indexed-parameters: true
        max-page-size: 200
    mongodb:
      uri: mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOST}/?retryWrites=true&w=majority&appName=Cluster0
      database: ${MONGODB_DATABASE}
      auto-index-creation: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

grpc:
  server:
    port: 9090
    enable-reflection: true